development:
            app_key: 12095462
            app_secret: 8ae1ea892912e2f8b83b2f2f1128177e
            rest_endpoint: http://gw.api.taobao.com/router/rest
            auth_url: http://container.open.taobao.com/container?appkey=

test:
            app_key: 12095462
            app_secret: 8ae1ea892912e2f8b83b2f2f1128177e
            rest_endpoint: http://gw.api.taobao.com/router/rest
            auth_url: http://container.open.taobao.com/container?appkey=

production:
            app_key: 12095462
            app_secret: 8ae1ea892912e2f8b83b2f2f1128177e
            rest_endpoint: http://gw.api.taobao.com/router/rest
            auth_url: http://container.open.taobao.com/container?appkey=
